logging:
  file: "logs/cas-config.log"
info:
  name : "central of configure"

---
server:
  # server port
  port: 8888
  # access url
  context-path: /config
spring:
  profiles:
    # local configure file
    active:
      - native
  application:
    # app name
    name: cas-config